on:
  workflow_call:
    inputs:
      publish_author_name:
        description: Name to use as author of publish commits
        required: true
        type: string
      publish_author_email:
        description: Email to use as author of publish commits
        required: true
        type: string
    secrets:
      github_pat:
        description: GitHub personal access token
        required: true

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache
        with:
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          path: node_modules
      - uses: actions/setup-node@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.2
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          run_install: true
          version: 7

  changed:
    name: Version changed packages
    runs-on: ubuntu-latest
    needs:
      - install
    outputs:
      jobs: ${{ steps.jobs.outputs.jobs }}
      packages: ${{ steps.packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          path: node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get changed packages
        id: packages
        run: echo "::set-output name=packages ::$((node_modules/.bin/lerna changed --loglevel silent || true) | paste -sd, -)"
      - name: Get jobs for changed packages
        if: steps.packages.outputs.packages != null
        id: jobs
        uses: chiel/action-get-jobs@v1
        with:
          packages: ${{ steps.packages.outputs.packages }}
      - name: Version changed packages
        if: steps.packages.outputs.packages != null
        run: node_modules/.bin/lerna version --no-git-tag-version --no-push
      - name: Upload version artifacts
        if: steps.packages.outputs.packages != null
        uses: actions/upload-artifact@v3
        with:
          name: version-artifacts
          path: packages/*/package.json

  packages-build:
    name: Build changed packages
    runs-on: ubuntu-latest
    needs:
      - changed
      - install
    if: needs.changed.outputs.packages != null
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache
        with:
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          path: node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/download-artifact@v3
        with:
          name: version-artifacts
          path: packages
      - name: Build changed packages
        run: node_modules/.bin/lerna run build --scope={,${{ needs.changed.outputs.packages }}} --include-dependencies
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: packages/*/dist

  docker-lint:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    needs:
      - changed
    if: |
      needs.changed.outputs.jobs != null &&
      fromJSON(needs.changed.outputs.jobs).docker-lint != null
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changed.outputs.jobs).docker-lint }}
    steps:
      - uses: actions/checkout@v3
      - name: Lint Dockerfiles
        uses: docker://hadolint/hadolint:latest-debian
        with:
          entrypoint: hadolint
          args: packages/${{ matrix.package }}/Dockerfile

  docker-build:
    name: Build Dockerfiles
    runs-on: ubuntu-latest
    needs:
      - changed
      - docker-lint
      - packages-build
    if: |
      needs.changed.outputs.jobs != null &&
      fromJSON(needs.changed.outputs.jobs).docker-build != null
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changed.outputs.jobs).docker-build }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: version-artifacts
          path: packages
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: packages
      - name: Determine version
        id: version
        run: |
          VERSION="v$(jq -r .version packages/${{ matrix.package }}/package.json)"
          echo "::set-output name=version ::$VERSION"
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_pat }}
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ghcr.io/${{ github.repository }}/${{ matrix.package }}:${{ steps.version.outputs.version }}
          context: packages/${{ matrix.package }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - changed
      - packages-build
      - docker-lint
      - docker-build
    if: |
      always() &&
      github.ref == 'refs/heads/master' &&
      needs.changed.outputs.packages != null &&
      needs.packages-build.result == 'success' &&
      (needs.docker-lint.result == 'success' || needs.docker-lint.result == 'skipped') &&
      (needs.docker-build.result == 'success' || needs.docker-build.result == 'skipped')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          path: node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: packages
      - name: Configure CI git user
        run: |
          git config --global user.name "${{ inputs.publish_author_name }}"
          git config --global user.email "${{ inputs.publish_author_email }}"
      - name: Version and commit packages
        run: node_modules/.bin/lerna version
      - name: Set GitHub Packages auth token
        run: |
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.github_pat }}' >> .npmrc
          git update-index --assume-unchanged .npmrc
      - name: Publish packages
        run: node_modules/.bin/lerna publish from-git --no-verify-access
